.travis.yml, cli/Valet/PackageManagers/Yum.php, cli/Valet/Valet.php
For the users who still using the PackageManager Yum (e.g. on CentOS) instead of Dnf ...
=> Added support for PackageManager Yum

cli/valet.php
This edit synchronises the version string for `valet -V` command with the current code tag.
=> Updated version number in `cli/valet.php`

.travis.yml, cli/Valet/Contracts/PackageManager.php, cli/Valet/DnsMasq.php, cli/Valet/Filesystem.php, cli/Valet/Nginx.php, cli/Valet/PackageManagers/Apt.php, cli/Valet/PackageManagers/Dnf.php, cli/Valet/PackageManagers/PackageKit.php, cli/Valet/PackageManagers/Pacman.php, cli/Valet/PackageManagers/Yum.php, cli/Valet/ServiceManagers/LinuxService.php, cli/Valet/ServiceManagers/Systemd.php, cli/scripts/update.sh, cli/stubs/dnsmasq, cli/stubs/dnsmasq.conf, cli/stubs/dnsmasq_options, cli/stubs/get-dns-servers, cli/stubs/networkmanager.conf, cli/stubs/resolved.conf, cli/stubs/secure.valet.conf, cli/valet.php, composer.json, server.php, tests/Functional/run.sh, tests/Integration/DnsMasqTest.php, tests/Integration/NginxTest.php, valet
This version includes a number of important fixes to the mechanics for getting the nameservers with dnsmasq.
Closes #7 
Fixes #86 
Resolves #95
=> Completely refactor the DNSMasq configuration

cli/Valet/Configuration.php, cli/Valet/DnsMasq.php, cli/drivers/KirbyValetDriver.php, cli/drivers/Typo3ValetDriver.php, readme.md, tests/Functional/InstallTest.php, tests/Functional/LinkTest.php, tests/Functional/ParkTest.php, tests/Functional/SecureTest.php, tests/Integration/DnsMasqTest.php, tests/Integration/NginxTest.php
Related to #98 cc @TheNodi ...
=> Default gTLD from *.dev to *.test

composer.json
=> Symfony Process ~4.0

cli/Valet/Nginx.php, cli/Valet/Site.php, cli/drivers/ValetDriver.php, cli/includes/helpers.php, cli/stubs/secure.valet.conf, cli/stubs/valet.conf, server.php
Cherry-Pick of https://github.com/laravel/valet/commit/6727e43288a8b29ce0151de44ca192e1c8592051
See #131
=> Use UUID for static asset path instead of "static"

cli/Valet/PhpFpm.php
=> Remove files param

cli/drivers/Magento2ValetDriver.php
With Magento 2.2 this small portion of code fixed rewrite problems with dev/static/sign
=> rewrite with static sign files

cli/Valet/PhpFpm.php
I noticed the changes in php version weren't kept after some restarts.
Which was because the old fpm service wasn't being disabled and the new one wasn't being enabled.
It was only being stopped and started.
So i added the code to disable the old service and enable the new service.
=> Disable old service and enable new service

index.md
made the instructions a bit clearer.
=> update uninstall instructions

cli/Valet/PackageManagers/Eopkg.php, cli/Valet/Valet.php
Related to https://github.com/cpriego/valet-linux/issues/125.
Todo:
- php-fpm come inside the package php (filter package name?)
- There is some problems with dnsmasq
=> Add support for Solus Package Manager - eopkg

cli/drivers/Magento2ValetDriver.php
**Related Issue:**
https://github.com/cpriego/valet-linux/issues/227
=> fix static files path issues with some of latest versions

server.php
https://github.com/laravel/valet/pull/830
=> Fix from upstream for paths containing a plus symbol

cli/valet.php
Hey there! :wave: 
There seem to be some issues with the latest version. Here's a PR to fix them.
Fixes https://github.com/cpriego/valet-linux/issues/245
Fixes https://github.com/cpriego/valet-linux/issues/244
Fixes https://github.com/cpriego/valet-linux/issues/242
- Context cannot be bound to static closures. When commands are created in Silly those closures are bound to command objects
- Default value shouldn't be set on options that are used as a flags. They will have value of `false` if not present and value of `true` if present.
P.S. Thanks for the great project! :slightly_smiling_face:
=> Fix various issues

cli/Valet/PhpFpm.php, cli/stubs/php-fpm.service.d/valet.conf, tests/Integration/PhpFpmTest.php
Alternative to #255 without changing the `valet.sock` location
@jmarcher
=> add dropIn override for systemd

server.php
Added Local network feature from
laravel#439
and
Resolves #257
and alternative to https://github.com/cpriego/valet-linux/pull/259
=> Added local network feature.

cli/stubs/valet-dns
this line should fix dns error
=> fix dns error

cli/Valet/Site.php
Issue: Valet Linux didn't use a CA certificate when running the `valet secure` command, this directly contributes to 
Fixes #187
Even though the original issue was closed, the proposed solution doesn't work because currently Valet Linux doesn't generate a CA certificate for use to sign website certificates.
This has been fixed in the same way as the original Laravel Valet used on Macs, now users can navigate to ~/.valet/CA and import the .pem cert chain into their authorities store whether on their OS (Linux or WSL) or into Firefox and their Valet hosted websites will show the normal padlock with no errors.
=> Make "valet secure" use a CA certificate, this allows users to import the CA into Firefox

composer.json
Added support for illuminate 8.0
=> support for illuminate 8.0

cli/drivers/SymfonyValetDriver.php
=> Enable support for Symfony 5.3+ (closes #334)

cli/valet.php
=> secure option for link

composer.json
Fixes clashes with `laravel/installer`
=> Allow newer package versions

cli/Valet/Site.php
Install certificates on each profile of firefox
ref : #367
=> fix - install certificates on firefox

server.php
Allow loading environment variable when serving site with valet( eg:ENVIRONEMENT=DEV, CONFIG_PATH=path/to/config)
=> add loading of environment variables (#277)

cli/valet.php
We have a update loop due to version mismatch
=> Bump version

cli/Valet/PhpFpm.php
Hi 👋
Since PR https://github.com/cpriego/valet-linux/pull/426 hasn't been updated and isn't getting merged, I've sent this PR to fix the issue. I believe this will make many Arch Linux users, including myself, happy.
=> Fix For Arch Linux

composer.json
Found 1 security vulnerability advisory affecting 1 package.
[nategood/](https://packagist.org/packages/nategood/)httpful
=> Vulnerability Security Fix

cli/Valet/PackageManagers/Apt.php, cli/Valet/PackageManagers/Homebrew.php
Is this all what needs to be changed?
Warning - I couldn't run the acceptance tests as I'm not setup with proper linux machine with both vagrant and vm provider software.
=> Add php@8.3 support
