cpriego/valet-linux

readme.md
It's already in the optional list.
=> Remove php*-mysql from required php packages

cli/includes/helpers.php
I was getting an error when running gulp on a project. Specifically "PHP Fatal error:  Cannot redeclare tap() (previously declared in /home/vince/.config/composer/vendor/illuminate/support/helpers.php:816) in /home/vince/.config/composer/vendor/cpriego/valet-ubuntu/cli/includes/helpers.php on line 123".
Checking to see if the function exists before redeclaring works great.
=> Prevent redeclaring tap function

cli/Valet/PackageManagers/Apt.php
for `dpkg -l 'php*cli' | grep '^ii' | sed 's_  _\\t_g' | cut -f 2` -> output
```
ii\tphp-cli\t\t\t\t1:7.0+35ubuntu6\t\t\t\t all\t\t\t\t\tcommand-line interpreter for the PHP scripting language (default)
ii\tphp-horde-cli\t2.0.6-3build1\t\t\t\t\t all\t\t\t\t\tHorde Command Line Interface API
ii\tphp7.0-cli\t\t 7.0.13-0ubuntu0.16.04.1 amd64\t\t\t\tcommand-line interpreter for the PHP scripting language
```
so I included digit regex
`dpkg -l 'php[0-9]*cli' | grep '^ii' | sed 's_  _\\t_g' | cut -f 2`
`ii\tphp7.0-cli\t\t 7.0.13-0ubuntu0.16.04.1 amd64\t\t\t\tcommand-line interpreter for the PHP scripting language`
=> Updated getPHPVersion() from cli/Valet/PackageManagers/Apt.php to include digit regex.

cli/stubs/valet.conf, tests/NginxTest.php
Hello,
Fixes : https://github.com/cpriego/valet-linux/issues/23
=> $query_string is not needed in nginx rewrite (#23)

cli/valet.php
The package's actual version is 2.0.10 but the `$version` var was still set to 2.0.9. This caused incorrect functionality for `valet on-latest-version` command.
=> Updated version number.

cli/Valet/Site.php
This will fix the message 'NET::ERR_CERT_WEAK_SIGNATURE_ALGORITHM' in Google Chrome
=> Sha256 for certs to fix weak-cert-signature in Chrome

cli/Valet/Site.php, cli/stubs/openssl.conf
This will fix/solve the '[subject CN matching](https://textslashplain.com/2017/03/10/chrome-deprecates-subject-cn-matching/)' (#54) deprecating in Chrome 58+, to add a 'SubjectAltName' for the certificate.
I tested it successfully on Chrome 58.0.3029.81 (64-bit) and Firefox (ESR) 52.1.0 (64-bit)
=> Added support for OpenSSL-SAN in Chrome 58+

cli/Valet/Site.php
Oops, I introduced a small bug after my previous pull-request (#57), which will recreate new *.conf files after switching domains (related to https://github.com/laravel/valet/pull/343)
=> Fix for switching domains/conf files

cli/Valet/PackageManagers/PackageKit.php, cli/Valet/Valet.php, tests/Integration/PackageKitTest.php
PackageKit attempts to create a cross-distro package manager and is supported on most popular ones.
While the distro specific package manager is probably preferred in most cases, having PackageKit as a fallback can be useful.
Especially on those that do not yet have support, (OpenSuSE, Mageia, Sabayon pops my mind.. :)).
Link to PackageKit: https://www.freedesktop.org/software/PackageKit
=> Add PackageKit as a Package manager.

cli/drivers/CraftValetDriver.php, cli/drivers/LaravelValetDriver.php, cli/drivers/Magento2ValetDriver.php, cli/drivers/NeosValetDriver.php, cli/drivers/SymfonyValetDriver.php, cli/drivers/Typo3ValetDriver.php, cli/drivers/ValetDriver.php, cli/drivers/require.php
There were some useful additions to Valet (specifically Magento, Neos and Typo3 drivers) and updates to existing drivers. I updated the drivers to be in sync with upstream without applying changes that haven't been implemented in valet-linux.
This also adds support for project-specific drivers.
=> Sync ValetDrivers with upstream, add support for LocalValetDriver

.travis.yml, develop, phpunit.xml, tests/Acceptance/Vagrant/.gitignore, tests/Acceptance/Vagrant/centos7/Vagrantfile, tests/Acceptance/Vagrant/centos7/provision.sh, tests/Acceptance/Vagrant/fedora25/Vagrantfile, tests/Acceptance/Vagrant/fedora25/provision.sh, tests/Acceptance/Vagrant/fedora26/Vagrantfile, tests/Acceptance/Vagrant/fedora26/provision.sh, tests/Acceptance/Vagrant/ubuntu1404/Vagrantfile, tests/Acceptance/Vagrant/ubuntu1404/provision.sh, tests/Acceptance/Vagrant/ubuntu1604/Vagrantfile, tests/Acceptance/Vagrant/ubuntu1604/provision.sh, tests/Acceptance/Vagrant/ubuntu1704/Vagrantfile, tests/Acceptance/Vagrant/ubuntu1704/provision.sh, tests/Acceptance/docker.sh, tests/Acceptance/vagrant.sh, tests/Functional/FunctionalTestCase.php, tests/Functional/InstallTest.php, tests/Functional/LinkTest.php, tests/Functional/ParkTest.php, tests/Functional/SecureTest.php, tests/Functional/ShareTest.php
I was trying to work on some features and realized this workflow is quite annoying. Every time I have to switch folder to spin up a virtual machine, configure it, test features, destroy it because my computer suffers etc. Docker didn't worked as well as I expected, so I decided to move one step up and use vagrant to "quickly" spin up some environments and run tests on them.
I know vagrant uses server boxes while Valet is intended for client usage, but it should be close enough to our needs. I expect network components to be the same on desktop and on server, minus the fancy GUIs.
There's one test failing, `ShareTest::test_we_can_share_an_https_site`, this is indeed a bug creating an infinite redirect when using Ngrok secure tunnels.
All commands are condensed into `./develop`, which has …
=> Vagrant Testing

cli/stubs/openssl.conf
This pull-request will add support for wildcard-ssl for domains, currently;
```
project.dev = works with ssl
foobar.project.dev = didn't works with ssl
```
to
```
project.dev = works with ssl
foobar.project.dev = works with ssl
foo.project.dev = works with ssl
etc
```
=> Added support for wildcard-ssl for domains

cli/Valet/Configuration.php, cli/Valet/Nginx.php, cli/Valet/PhpFpm.php, cli/Valet/Site.php, cli/includes/helpers.php, cli/stubs/secure.valet.conf, cli/valet.php, tests/Functional/ShareTest.php, valet
Add a command to configure a custom HTTPS port:
```
valet port --https 44343
```
This should be backwards compatible since it default to 443 if no port is specified.
Also fixed:
- `valet links` not considering custom port
- `valet share` on secured site (See #107 )
=> HTTPS port

server.php
Valet doesn't support mix-case domains if you request a domain with uppercase characters.
`curl http://someDomain.test` will result in a `404 - Valet Not Found` even if `someDomain` folder exists. 
See https://github.com/cpriego/valet-linux/issues/128#issuecomment-358134245 for detailed explanation.
The solution is to lowercase the host parameter before matching it with folder slug (which is already lowercased).
=> Support mix-case domains

cli/stubs/secure.valet.conf, server.php, valet
This is a backport of 
https://github.com/laravel/valet/pull/630
=> Allow secured sites to be shared

.travis.yml, composer.json
This will stop anyone from trying to use Valet with PHP <= 5.6 as it will not work out of the box. You can get around it with a bunch of work.
See
- #205
- laravel#742
- laravel#727
=> Enforcing php >= 7.0

cli/Valet/PhpFpm.php, cli/valet.php
Since i really enjoyed the `valet use` command from valetplus i added it in as a command.
This first stops the current php-fpm service, and (installs if needed) and runs the new php-fpm service.
after which it will add a file in the VALET_HOME_PATH with the current preferred fpm version which will convince valet that that is the current php version and will launch the new preferred version of php-fpm
Tested on Ubuntu 18.04 switching php 7.2 and php 7.3
=> Implemented php-fpm version switcher as `valet use`.

valet
This fixes the issue that occurs when `valet share` failed to start ngrok because of valet.php tool ANSI output for `domain` configuration value.
I fixed the issue on my Ubuntu computer by reading the domain TLD from `$HOME/.valet/config.json` instead just like when reading the PORT.
The error message that occurs before I fix it, notice the ANSI green domain name:
=> fix: ngrok strange hostname error when sharing

cli/Valet/CommandLine.php, composer.json
Passing a command as string is deprecated since Symfony 4.2.
More information at [https://github.com/laravel/valet/pull/761](url)
=> Updates symfony/process dependency to 5.0 and fixes deprecated Process argument passed as string

cli/stubs/dnsmasq_options
This solved a problem I had after installing valet where I couldn't resolve any names defined only inside a vpn. These two extra options will simply tell dnsmasq to look at all of the defined nameservers (/var/opt/valet-linux/dns-servers) and query each of them in order.
=> add options to query all nameservers

cli/stubs/secure.valet.conf, cli/stubs/valet.conf
Some versions of WSL with PHP-FPM may sometimes completely hang and not load if proxy_buffering is not set to off.
It's also the standard in production to disable buffering for fastcgi.
=> Add fastcgi_buffering to off

cli/Valet/Nginx.php, cli/Valet/PhpFpm.php, cli/valet.php
For example if your php version is `7.3` and you want to switch to `7.4` with `valet use 7.4` the FPM version will be changed but the CLI version still `7.3` when call `php -v`, So this PR. fix that.
=> Change CLI & FPM version when call 'valet use' command

valet
Fedora 33 locks php 7.4 and up, when using a remi repository you are forced to use a software collection for lower versions, but without using a login shell for sudo, the php command won't be available.
This just adds `-i` where valet tries to use sudo to enforce a login shell to use the version of php you have set for cli. Not sure if it would have any other repercussions or if there is a better way around it.
To reproduce this issue, look at the remi wizard https://rpms.remirepo.net/wizard/ and find a distro of linux that does not allow you to use a specific version of php without using a software collection (fedora 32/33 work for this) set up a machine using that distro and setup php with remi to use a version like 7.3 for fedora 32/33. Valet will fail any command it needs sudo for …
=> Use -i for sudo for login shell

cli/stubs/openssl.conf
The latest browsers (Chrome, FF, Edge, etc) don't view the currently generated OpenSSL certs as valid, this change fixes this by specifying the key usage parameters, as well as defaulting the key size to 2048.
=> Fix valet secure on latest browsers

cli/stubs/dnsmasq_options
Currently there is an issue with NetworkManager created WireGuard instances, that it will correctly add/update the VPN's DNS servers to /etc/valet-linux/dns-servers, but dnsmasq ignores the new DNS server. Adding this flag forces it to use the first entry of the dns-servers file which would be the wanted DNS server.
=> Add strict-order flag to dnsmasq options, providing better support for VPN DNS servers

composer.json, tests/Functional/InstallTest.php, tests/Functional/LinkTest.php, tests/Functional/ParkTest.php, tests/Functional/SecureTest.php, tests/Functional/ShareTest.php, tests/Integration/AptTest.php, tests/Integration/ConfigurationTest.php, tests/Integration/DnsMasqTest.php, tests/Integration/FilesystemTest.php, tests/Integration/LinuxServiceTest.php, tests/Integration/NginxTest.php, tests/Integration/PackageKitTest.php, tests/Integration/PhpFpmTest.php, tests/Integration/RequirementsTest.php, tests/Integration/SiteTest.php
This PR will add missing compatibility to tests, especially, on `setUp` and `tearDown` functions to be:
```diff
-    protected function setUp()
+    protected function setUp(): void
-    protected function tearDown()
+    protected function tearDown(): void
```
Also, will change deprecated mockery function `assertFileNotExists()` to `assertFileDoesNotExist()` and fix some tests as will.
=> Add compatibility to tests classes

cli/stubs/valet-dns
Hi,
With my Ubuntu 20.04 install, 127.0.0.53 was included in one of the resolv files valet-dns scrapes when looking for nameservers.
I believe this IP, like 127.0.0.1, should be excluded to prevent slow DNS lookups due to an infinite loop lookup (until a timeout occurs).
This change will exclude the entire loopback range, instead of just 127.0.0.1.
Thanks for considering this pull.
Cheers
=> Exclude entire loopback range from DNS file

cli/valet.php
Hey @Adesin-fr 
The current release is `v2.2.35` now prefixed with `v`, but the Version wasn't bumped in the code itself so the `valet update` command still tries to update every time.
Please merge this and release `v2.2.36` and keep in mind to bump the version before each release.
Cheers Adrian.
=> bump version

cli/Valet/Site.php, cli/valet.php, tests/Integration/PhpFpmTest.php
`getLinks()` now returns the same data structure as `getSites()` and can be used together to find a site to isolate (the `->where('site', $site)` didn't find links)
`PhpFpmTest::test_install_configuration_replaces_user_and_sock_in_config_file` doesn't pass but I think is not related to my edits.
=> fix isolate

composer.json
I guess the change in the package name was changed unintentionally.
I noticed it as I keep a local fork with some patches and composer wasn't respecting the "repositories" property, and was trying to download from packagist instead.
=> Revert package name in composer.json
